// Utilitário de Tradução Dinâmica para a Versão Judaica Completa (Estilo David Stern)
// Preserva os nomes hebraicos originais e terminologia judaica fiel aos manuscritos originais.

const judaicBookNames: Record<string, string> = {
  gn: 'Bereshit (Gênesis)',
  ex: 'Shemot (Êxodo)',
  lv: 'Vayikra (Levítico)',
  nm: 'Bemidbar (Números)',
  dt: 'Devarim (Deuteronômio)',
  js: 'Yehoshua (Josué)',
  jz: 'Shoftim (Juízes)',
  rt: 'Rut (Rute)',
  '1sm': 'Shmuel Alef (1º Samuel)',
  '2sm': 'Shmuel Bet (2º Samuel)',
  '1rs': 'Melakhim Alef (1º Reis)',
  '2rs': 'Melakhim Bet (2º Reis)',
  '1cr': 'Divrei-HaYamim Alef (1º Crônicas)',
  '2cr': 'Divrei-HaYamim Bet (2º Crônicas)',
  ed: 'Ezra (Esdras)',
  ne: 'Nechemyah (Neemias)',
  et: 'Ester',
  jó: 'Iyov (Jó)',
  sl: 'Tehillim (Salmos)',
  pv: 'Mishlei (Provérbios)',
  ec: 'Kohelet (Eclesiastes)',
  ct: 'Shir-HaShirim (Cantares)',
  is: 'Yesha\'yahu (Isaías)',
  jr: 'Yirmeyahu (Jeremias)',
  lm: 'Eikhah (Lamentações)',
  ez: 'Yechezk\'el (Ezequiel)',
  dn: 'Daniel',
  os: 'Hoshea (Oseias)',
  jl: 'Yo\'el (Joel)',
  am: 'Amos',
  ob: 'Obadyah (Obadias)',
  jn: 'Yonah (Jonas)',
  mq: 'Mikhah (Miqueias)',
  na: 'Nachum (Naum)',
  hc: 'Chavakuk (Habacuque)',
  sf: 'Tzefanyah (Sofonias)',
  ag: 'Chaggai (Ageu)',
  zc: 'Zekharyah (Zacarias)',
  ml: 'Mal\'akhi (Malaquias)',
  mt: 'Mattityahu (Mateus)',
  mc: 'Markos (Marcos)',
  lc: 'Lukas (Lucas)',
  jo: 'Yochanan (João)',
  at: 'Atos dos Emissários',
  rm: 'Romanos',
  '1co': '1ª Coríntios',
  '2co': '2ª Coríntios',
  gl: 'Gálatas',
  ef: 'Efésios',
  fp: 'Filipenses',
  cl: 'Colossenses',
  '1ts': '1ª Tessalonicenses',
  '2ts': '2ª Tessalonicenses',
  '1tm': '1ª Timóteo',
  '2tm': '2ª Timóteo',
  tt: 'Tito',
  fm: 'Filemom',
  hb: 'Hebreus',
  tg: 'Ya\'akov (Tiago)',
  '1pe': 'Kefa Alef (1ª Pedro)',
  '2pe': 'Kefa Bet (2ª Pedro)',
  '1jo': 'Yochanan Alef (1ª João)',
  '2jo': 'Yochanan Bet (2ª João)',
  '3jo': 'Yochanan Guimel (3ª João)',
  jd: 'Yehudah (Judas)',
  ap: 'Revelação (Chazon)'
};

const judaicCategories: Record<string, string> = {
  'A Lei (Torá)': 'Torá (A Lei)',
  'Históricos': 'Nevi\'im Rishonim (Profetas Anteriores / Históricos)',
  'Poéticos': 'Ketuvim (Escritos / Poéticos)',
  'Profetas Maiores': 'Nevi\'im Acharonim (Profetas Posteriores Maiores)',
  'Profetas Menores': 'Nerei Asar (Os Doze Profetas Menores)',
  'Evangelhos': 'Besorot (Evangelhos)',
  'Histórico': 'Histórico (Atos)',
  'Epístolas Paulinas': 'Cartas de Sha\'ul (Paulo)',
  'Epístolas Gerais': 'Cartas Gerais',
  'Profético': 'Chazon (Revelação)'
};

const judaicTermsMap: Array<[RegExp, string]> = [
  // 1. Divine Names
  [/\bDeus\b/g, 'Elohim'],
  [/\bdeus\b/g, 'elohim'],
  [/\bDeuses\b/g, 'elohim'],
  [/\bdeuses\b/g, 'elohim'],
  [/\bSENHOR\b/g, 'Adonai'],
  [/\bSenhor\b/g, 'Adonai'],
  [/\bsenhor\b/g, 'adonai'],
  [/\bSENHORES\b/g, 'adonai'],
  [/\bSenhores\b/g, 'adonai'],
  [/\bJHVH\b/g, 'YHWH'],
  [/\bjhvh\b/g, 'yhwh'],
  [/\bJEOVÁ\b/g, 'YHWH'],
  [/\bJeová\b/g, 'YHWH'],
  [/\bjeová\b/g, 'yhwh'],
  [/\bIehouah\b/gi, 'YAHUAH'],
  [/\bIEHOUAH\b/gi, 'YAHUAH'],
  
  // 2. Messianic / Theological Terms
  [/\bJesus\b/g, 'Yeshua'],
  [/\bCristo\b/g, 'o Messias'],
  [/\bcristo\b/g, 'o messias'],
  [/\bEspírito\s+Santo\b/gi, 'Ruach HaKodesh'],
  [/\bapóstolo\b/g, 'emissário'],
  [/\bapóstolos\b/g, 'emissários'],
  [/\bApóstolo\b/g, 'Emissário'],
  [/\bApóstolos\b/g, 'Emissários'],
  [/\bigreja\b/g, 'congregação'],
  [/\bigrejas\b/g, 'congregações'],
  [/\bIgreja\b/g, 'Congregação'],
  [/\bIgrejas\b/g, 'Congregações'],
  [/\bdiscípulo\b/g, 'talmid'],
  [/\bdiscípulos\b/g, 'talmidim'],
  [/\bDiscípulo\b/g, 'Talmid'],
  [/\bDiscípulos\b/g, 'Talmidim'],
  [/\bpecado\b/g, 'transgressão'],
  [/\bpecados\b/g, 'transgressões'],
  [/\bPecado\b/g, 'Transgressão'],
  [/\bPecados\b/g, 'Transgressões'],
  [/\bbatismo\b/g, 'imersão'],
  [/\bbatismos\b/g, 'imersões'],
  [/\bBatismo\b/g, 'Imersão'],
  [/\bbatizar\b/g, 'imergir'],
  [/\bbatizou\b/g, 'imergiu'],
  [/\bbatizado\b/g, 'imergido'],
  [/\bbatizados\b/g, 'imergidos'],
  [/\bBatizar\b/g, 'Imergir'],
  [/\bBatizou\b/g, 'Imergiu'],
  [/\bBatizado\b/g, 'Imergido'],
  [/\bBatizados\b/g, 'Imergidos'],
  [/\banjo\b/g, 'mensageiro (malakh)'],
  [/\banjos\b/g, 'mensageiros (malakhim)'],
  [/\bAnjo\b/g, 'Mensageiro (Malakh)'],
  [/\bAnjos\b/g, 'Mensageiros (Malakhim)'],
  [/\bevangelho\b/g, 'boas-novas'],
  [/\bEvangelho\b/g, 'Boas-Novas'],
  [/\blei\b/g, 'Torá'],
  [/\bLei\b/g, 'Torá'],
  [/\baliança\b/g, 'aliança (covenant)'],
  [/\bAliança\b/g, 'Aliança (Covenant)'],
  [/\bsacerdote\b/g, 'cohen'],
  [/\bsacerdotes\b/g, 'cohanim'],
  [/\bSacerdote\b/g, 'Cohen'],
  [/\bSacerdotes\b/g, 'Cohanim'],
  [/\bsacerdócio\b/g, 'cohenato'],
  [/\bsanto\b/g, 'kadosh'],
  [/\bsantos\b/g, 'kedoshim'],
  [/\bSanto\b/g, 'Kadosh'],
  [/\bSantos\b/g, 'Kedoshim'],

  // 3. Biblical Names (Hebrew Restorations)
  [/\bMoisés\b/g, 'Moshe'],
  [/\bAbraão\b/g, 'Avraham'],
  [/\bIsaque\b/g, 'Yitzchak'],
  [/\bJacó\b/g, 'Ya\'akov'],
  [/\bSalomão\b/g, 'Shlomo'],
  [/\bDavi\b/g, 'David'],
  [/\bPaulo\b/g, 'Sha\'ul'],
  [/\bPedro\b/g, 'Kefa'],
  [/\bJoão\b/g, 'Yochanan'],
  [/\bMateus\b/g, 'Mattityahu'],
  [/\bMarcos\b/g, 'Markos'],
  [/\bLucas\b/g, 'Lukas'],
  [/\bTiago\b/g, 'Ya\'akov'],
  [/\bJudas\b/g, 'Yehudah'],
  [/\bMaria\b/g, 'Miryam'],
  [/\bJosé\b/g, 'Yosef'],
  [/\bElias\b/g, 'Eliyahu'],
  [/\bEliseu\b/g, 'Elisha'],
  [/\bIsaías\b/g, 'Yesha\'yahu'],
  [/\bJeremias\b/g, 'Yirmeyahu'],
  [/\bEzequiel\b/g, 'Yechezk\'el'],
  [/\bOseias\b/g, 'Hoshea'],
  [/\bJoel\b/g, 'Yo\'el'],
  [/\bObadias\b/g, 'Obadyah'],
  [/\bJonas\b/g, 'Yonah'],
  [/\bMiqueias\b/g, 'Mikhah'],
  [/\bNaum\b/g, 'Nachum'],
  [/\bHabacuque\b/g, 'Chavakuk'],
  [/\bSofonias\b/g, 'Tzefanyah'],
  [/\bAgeu\b/g, 'Chaggai'],
  [/\bZacarias\b/g, 'Zekharyah'],
  [/\bMalaquias\b/g, 'Mal\'akhi'],
  [/\bEnoque\b/g, 'Chanokh'],
  [/\bNoé\b/g, 'Noach'],
  [/\bMelquisedeque\b/g, 'Malki-Tzedek'],
  [/\bSara\b/g, 'Sarah'],
  [/\bRebeca\b/g, 'Rivkah'],
  [/\bRaquel\b/g, 'Rachel'],
  [/\bLia\b/g, 'Leah'],
  [/\bFaraó\b/g, 'Par\'oh'],
  [/\bSinai\b/g, 'Sinai'],
  [/\bSinaí\b/g, 'Sinai'],
  [/\bJerusalém\b/g, 'Yerushalayim'],
  [/\bEgito\b/g, 'Mitzrayim'],
  [/\bBabilônia\b/g, 'Bavel']
];

export const translateToJudaic = (text: string, isActive: boolean = true): string => {
  if (!isActive || !text) return text;
  let result = text;
  for (const [regex, replacement] of judaicTermsMap) {
    result = result.replace(regex, replacement);
  }
  return result;
};

export const getJudaicBookName = (abbrev: string, defaultName: string, isActive: boolean = true): string => {
  if (!isActive) return defaultName;
  const lower = abbrev.toLowerCase();
  return judaicBookNames[lower] || defaultName;
};

export const getJudaicCategory = (category: string, isActive: boolean = true): string => {
  if (!isActive) return category;
  return judaicCategories[category] || category;
};

export const getJudaicTransliteration = (translit: string, isActive: boolean = true): string => {
  if (!isActive || !translit) return translit;
  return translit.replace(/\bYHVH\b/g, 'YHWH').replace(/\byhvh\b/g, 'yhwh');
};
